#!/usr/bin/env bash

# AWS Comprehend
export BM_AWS_COMPREHEND_REGION='us-east-1';
export BM_AWS_COMPREHEND_ACCESS_KEY_ID='AKIAT7WAUYD3SJOS26FU';
export BM_AWS_COMPREHEND_SECRET_ACCESS_KEY='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';

export BM_TWITTER_BEARER_TOKEN='AAAAAAAAAAAAAAAAAAAAAK34dQEAAAAAvgCEwtFXVmYgnTmye%2BYPb377czA%3Dh7AfMiZ5EJf4rknj7nn3O6qG9XBSloNnySWLyMCe7MZZQpKYB0'

